### ISSUE TITLE
bad file descriptor

### ISSUE THREAD

**Issue by sanfx** [hlamer/cpp2python#1]
macHost:cpp2python sanjeevkumar$ mv setDeepData.py setDeepData.cpp
macHost:cpp2python sanjeevkumar$ python cpp2python.py setDeepData.cpp 
Traceback (most recent call last):
  File "cpp2python.py", line 299, in <module>
    process_file(sys.argv[1])
  File "cpp2python.py", line 276, in process_file
    file.truncate(0)
IOError: [Errno 9] Bad file descriptor

Guess your background is cpp, however I want to add to your attempt in a python module you do not add #!/usr/bin env python but to a python executable script without py extension.
and instead of help ="""
whatever help content is """

it has to be defined in function as docString should be.

**Comment by andreikop** [comment]
Hi

> IOError: [Errno 9] Bad file descriptor

I can't reproduce it. What is mode of your file? (`ls -l`)
Could you run `strace python cpp2python.py YOURFILE` and check the output?

> you do not add #!/usr/bin env python but to a python executable script without py extension.

I do not understand this text. If the script doesn't have `#!/usr/bin env`, how an OS would understand how to run it?
.py suffix is useless on unixes, but, I'm not sure about Windows. Except this, some text editors need .py to recognize, how to highlight the file.

> instead of help =""" whatever help content is """ 
> it has to be defined in function as docString should be.

My Python background says me, that docStrings are useful as a documentation for public modules, classes and funcitons. But cpp2python doesn't export any API to other modules. Help message at the start is a cmdline utility description, which shall by printed to console by script itself, but should not be recognized by documentation tools.

**Comment by andreikop** [comment]
Can not reproduce
