### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thezakman** [hlamer/cpp2python#5]
when installing:

installing library code to build/bdist.linux-i686/egg
running install_lib
warning: install_lib: 'build/lib.linux-i686-2.7' does not exist -- no Python modules to install

root@darkmatter#  cpp2python sample.c

Traceback (most recent call last):
  File "/usr/local/bin/cpp2python", line 9, in <module>
    load_entry_point('cpp2python==0.2.0', 'console_scripts', 'cpp2python')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
ImportError: No module named cpp2python
root@darkmatter:~/Desktop/CTF-Challenges

**Comment by andreikop** [comment]
@stuaxo, maybe you can look at this?
I'm having the same problem on Mint 16

**Comment by stuaxo** [comment]
Sure, I've got a mint vm, will give it a go ..

**Comment by stuaxo** [comment]
It "works for me" on Mint 17, 32 Bit ... I'll need to get a version 16 VM and retry.

Can you paste the exact commands you used to grab the source and their output ?

Here is what I did:

``` bash
$ sudo apt-get install python python-setuptools git
$ git clone https://github.com/hlamer/cpp2python
$ cd cpp2python
$ sudo python setup.py install
```

After that I'm able to run `cpp2python` 

(I haven't pasted the full output as I need to sort out the guest extensions)

**Comment by andreikop** [comment]
@stuaxo, I also do `sudo python setup.py install`, repo is cloned, packages are installed.

Hmm, but my box should not be used as a reference since I have Mint 16 + trusty repositories enabled. It can be considered as broken installation.

@thezakman, which distribution do you use?

**Comment by thezakman** [comment]
I used Debian, will post The output when i get home.

**Comment by andreikop** [comment]
@stuaxo, here is my output on Linux Mint 17.2 (based on Ubuntu 14.04)

```
a@a-desktop ~/code/cpp2python (master)$ sudo python setup.py  install 
[sudo] password for a: 
running install
running bdist_egg
running egg_info
creating cpp2python.egg-info
writing cpp2python.egg-info/PKG-INFO
writing top-level names to cpp2python.egg-info/top_level.txt
writing dependency_links to cpp2python.egg-info/dependency_links.txt
writing entry points to cpp2python.egg-info/entry_points.txt
writing manifest file 'cpp2python.egg-info/SOURCES.txt'
reading manifest file 'cpp2python.egg-info/SOURCES.txt'
writing manifest file 'cpp2python.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cpp2python.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cpp2python.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cpp2python.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cpp2python.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cpp2python.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/cpp2python-0.2.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cpp2python-0.2.0-py2.7.egg
Copying cpp2python-0.2.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding cpp2python 0.2.0 to easy-install.pth file
Installing cpp2python script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/cpp2python-0.2.0-py2.7.egg
Processing dependencies for cpp2python==0.2.0
Finished processing dependencies for cpp2python==0.2.0
```

```
a@a-desktop ~/code/cpp2python (master)*$ cpp2python 
Traceback (most recent call last):
  File "/usr/local/bin/cpp2python", line 9, in <module>
    load_entry_point('cpp2python==0.2.0', 'console_scripts', 'cpp2python')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named cpp2python
a@a-desktop ~/code/cpp2python (master)*$ 
```

**Comment by stuaxo** [comment]
It looks like those are two different pythons - when you use sudo it's using the one in /usr/local and when you are the user it's using the /usr

**Comment by stuaxo** [comment]
If `$ which python` outputs `/usr/bin/python` then install it with   `sudo /usr/bin/python setup.py install`

**Comment by andreikop** [comment]
`cpp2python` is installed to `local`, but I have only 1 Python interpreter at `/usr/bin`

**Comment by stuaxo** [comment]
Oh, yeah - weird. 

I can try and get an iso of 17.2 and see what happens, certainly on the 17.1 version I'm able to install git, python-setuptools and install it fine ..

**Comment by stuaxo** [comment]
Yay, reproduced it.. think it only worked as I was testing from a particular directory .. testing fix now ..

**Comment by thezakman** [comment]
Thanks for fixing this!
