### ISSUE TITLE
Not working on Python 2.7

### ISSUE THREAD

**Issue by gbstack** [hlamer/cpp2python#9]
This commit 9bcbbe75187d3ff96e48aa92bb684286c90a4b34 made some changes that it cannot work on Python 2.7 anymore.

How to reproduce (Python 2.7 on Windows):

> python cpp2python.py qhexedit.cpp

It will raise SyntaxError: invalid syntax

Maybe we can create a new branch for Python 3, or add some Python 3 specific code when detected Python 3 is used.

**Comment by andreikop** [comment]
I updated README and the script. Now Python3 is used by default. I don't think if makes sense to support 2 versions for one-time script used by a developers
